# Generated by Django 3.1.4 on 2020-12-03 20:15

from django.db import migrations
import image_optimizer.fields


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20201201_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=image_optimizer.fields.OptimizedImageField(default='avatar.png', upload_to='avatars/'),
        ),
    ]
